export interface IEmoji {
    'added_in': string,
    'au': string,
    'category': string,
    'docomo': string,
    'google': string,
    'has_img_apple': boolean,
    'has_img_facebook': boolean,
    'has_img_google': boolean,
    'has_img_twitter': boolean,
    'image': string,
    'name': string,
    'non_qualified': unknown,
    'sheet_x': number,
    'sheet_y': number,
    'short_name': string,
    'short_names': Array<string>,
    'softbank': string,
    'sort_order': number,
    'text': string,
    'texts': Array<string>,
    'unified': string
}
